# example values

indexing-settings:
  user-agent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referrer: "http://www.google.com"
  sites:
#    - url: https://lenta.ru/
#      name: Лента.ру
#    - url: https://skillbox.ru/
#      name: Skillbox
#    - url: https://playback.ru/
#      name: PlayBack
#    - url: https://energyfm.ru/
#      name: Энерджи
#    - url: https://vgtrk.ru/
#      name: РадиоРоссии
    - url: https://sendel.ru/
      name: Sendel
#    - url: https://nashe.ru/
#      name: Наше
#    - url: https://afisha.ru/
#      name: Афиша
#    - url:  https://et-cetera.ru/mobile/
#      name: Эт Сэтера
#    - url: https://vipavenue.ru/
#      name: Vipavenue


server:
  port: 8080
spring:
  datasource:
    username: root
    password: Dimat12345
    url:
     jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
#    show-sql: true
    jdbc:
      batch_size: 1000
      order_inserts: true
      order_updates: true

